### ISSUE TITLE
Sonic Pi Boot Error (PopOS)

### ISSUE THREAD

**Issue by SamKomesarook** [flathub/net.sonic_pi.SonicPi#5]
Hey!

I've downloaded Sonic Pi through the Pop!_Shop flatpak channel, however it will not open successfully.

When I download it via the Ubuntu channel, version 2.10.0~repack-2.1, it runs fine!

### System Information
Sonic Pi version: 3.3.1
OS: Pop!_OS 20.10

### GUI Log
`/home/pi/.sonic-pi/log/gui.log`
```
[GUI] -                            
[GUI] -                            
[GUI] -                            
[GUI] - Welcome to the Sonic Pi GUI
[GUI] - ===========================
[GUI] -                            
[GUI] - {4075cab2-07f9-4b57-b543-6166994d71d6}
[GUI] - ui locale:  en-AU
[GUI] - sys locale: en_AU
[GUI] - translations available 
[GUI] - Discovering port numbers...
[GUI] - Port entry server-listen-to-gui : 51235 : 51235
[GUI] - Port entry gui-send-to-server : 51235 : 51235
[GUI] - Port entry gui-listen-to-server : 51236 : 51236
[GUI] - Port entry server-send-to-gui : 51236 : 51236
[GUI] - Port entry scsynth : 51237 : 51237
[GUI] - Port entry scsynth-send : 51237 : 51237
[GUI] - Port entry server-osc-cues : 4560 : 4560
[GUI] - Port entry erlang-router : 51238 : 51238
[GUI] - Port entry websocket : 51239 : 51239
[GUI] - Detecting port numbers...
[GUI] - GUI listen to server port 51236
[GUI] -    port: 51236 [OK]
[GUI] - Server listen to gui port 51235
[GUI] -    port: 51235 [OK]
[GUI] - Server incoming OSC cues port 4560
[GUI] -    port: 4560 [OK]
[GUI] - Scsynth port 51237
[GUI] -    port: 51237 [OK]
[GUI] - Server send to GUI port 51236
[GUI] -    port: 51236 [OK]
[GUI] - GUI send to server port 51235
[GUI] -    port: 51235 [OK]
[GUI] - Scsynth send port 51237
[GUI] -    port: 51237 [OK]
[GUI] - Erlang router port 51238
[GUI] -    port: 51238 [OK]
[GUI] - Websocket port 51239
[GUI] -    port: 51239 [OK]
[GUI] - All ports OK
[GUI] - hiding main window
[GUI] - initialising toolbar icons
[GUI] - setting up window structure
[GUI] - restoring scope states 
[GUI] - creating status bar
[GUI] - creating info panel
[GUI] - creating shortcuts
[GUI] - creating tool bar
[GUI] - initialising documentation window
[GUI] - launching Sonic Pi Runtime Server:
[GUI] - starting UDP OSC Server on port 51236...
[GUI] - UDP OSC Server ready and listening
[GUI] - Ruby server pid registered: 26
[GUI] - wait for sync
[GUI] - waiting for Sonic Pi Server to boot...
...............................
[GUI] - Sonic Pi Server failed to start with this error message: 
      > Server Exception:
 Boot - Unable to connect to SuperCollider
 ["/app/app/server/ruby/lib/sonicpi/scsynthexternal.rb:296:in `boot_and_wait'", "/app/app/server/ruby/lib/sonicpi/scsynthexternal.rb:462:in `boot_server_linux'", "/app/app/server/ruby/lib/sonicpi/scsynthexternal.rb:172:in `boot'", "/app/app/server/ruby/lib/sonicpi/scsynthexternal.rb:58:in `initialize'", "/app/app/server/ruby/lib/sonicpi/server.rb:80:in `new'", "/app/app/server/ruby/lib/sonicpi/server.rb:80:in `initialize'", "/app/app/server/ruby/lib/sonicpi/studio.rb:117:in `new'", "/app/app/server/ruby/lib/sonicpi/studio.rb:117:in `init_scsynth'", "/app/app/server/ruby/lib/sonicpi/studio.rb:52:in `initialize'", "/app/app/server/ruby/lib/sonicpi/lang/sound.rb:89:in `new'", "/app/app/server/ruby/lib/sonicpi/lang/sound.rb:89:in `block (2 levels) in included'", "/app/app/server/ruby/lib/sonicpi/lang/ixi.rb:72:in `block (2 levels) in included'", "/app/app/build/gui/qt/../../../../app/server/ruby/bin/sonic-pi-server.rb:344:in `new'", "/app/app/build/gui/qt/../../../../app/server/ruby/bin/sonic-pi-server.rb:344:in `<main>'"]
[GUI] - UDP OSC Server no longer listening
.............................
[GUI] - Critical error! Could not boot Sonic Pi Server.
[GUI] - stopping UDP OSC Server...
[GUI] - Critical Error. Unable to connect to server..
```
### Server Errors
`/home/pi/.sonic-pi/log/gui.log`
```sh: line 1: exec: jackd: not found
[W][000254920.385558][module-rtkit.c:185 translate_error()] RTKit error: org.freedesktop.DBus.Error.Failed
[W][000254920.385657][module-rtkit.c:519 set_nice()] could not set nice-level to -11: Input/output error
[W][000254920.387530][module-rtkit.c:185 translate_error()] RTKit error: org.freedesktop.DBus.Error.Failed
[W][000254920.387574][module-rtkit.c:506 idle_func()] could not make thread realtime: Input/output error
```
### Server Output
`/home/pi/.sonic-pi/log/server-output.log`
```
Sonic Pi server booting...
The time is 2021-04-30 15:07:43 +1000
Using primary protocol: udp
Detecting port numbers...
Listen port: 51235
  - OK
Scsynth port: 51237
  - OK
Scsynth send port: 51237
  - OK
OSC cues port: 4560
  - OK
Erlang port: 51238
  - OK
Websocket port: 4562
  - OK
Opening UDP Server to listen to GUI on port: 51235
Starting Server Runtime
Booting server...


Booting Sonic Pi
----------------

Booting on Linux
Jackd not running on system. Starting...
Boot - Starting the SuperCollider server...
Started [39] [-] sh [-] /var/tmp/sonic-pi-pids/39
Started [41] [-] scsynth -u 51237 -a 1024 -m 131072 -D 0 -R 0 -l 1 -i 16 -o 16 -b 4096 -B 127.0.0.1 [-] /var/tmp/sonic-pi-pids/41
Boot - SuperCollider booted successfully.
Boot - Connecting to the SuperCollider server...
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Sending /status to server: 127.0.0.1:51237
Boot - Unable to connect to SuperCollider
Failed to start server: Boot - Unable to connect to SuperCollider
/app/app/server/ruby/lib/sonicpi/scsynthexternal.rb:296:in `boot_and_wait'
/app/app/server/ruby/lib/sonicpi/scsynthexternal.rb:462:in `boot_server_linux'
/app/app/server/ruby/lib/sonicpi/scsynthexternal.rb:172:in `boot'
/app/app/server/ruby/lib/sonicpi/scsynthexternal.rb:58:in `initialize'
/app/app/server/ruby/lib/sonicpi/server.rb:80:in `new'
/app/app/server/ruby/lib/sonicpi/server.rb:80:in `initialize'
/app/app/server/ruby/lib/sonicpi/studio.rb:117:in `new'
/app/app/server/ruby/lib/sonicpi/studio.rb:117:in `init_scsynth'
/app/app/server/ruby/lib/sonicpi/studio.rb:52:in `initialize'
/app/app/server/ruby/lib/sonicpi/lang/sound.rb:89:in `new'
/app/app/server/ruby/lib/sonicpi/lang/sound.rb:89:in `block (2 levels) in included'
/app/app/server/ruby/lib/sonicpi/lang/ixi.rb:72:in `block (2 levels) in included'
/app/app/build/gui/qt/../../../../app/server/ruby/bin/sonic-pi-server.rb:344:in `new'
/app/app/build/gui/qt/../../../../app/server/ruby/bin/sonic-pi-server.rb:344:in `<main>'
```
### SCSynth Log
`/home/pi/.sonic-pi/log/scsynth.log`
```
# Starting SuperCollider 2021-04-30 15:07:43
Found 0 LADSPA plugins
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
SuperCollider 3 server ready.
```
### Process Log
`/home/pi/.sonic-pi/log/process.log`
```

	ask-clear.rb


Clearing pids: []
No pids to clear :-)
Started [26] [-] /app/bin/ruby --enable-frozen-string-literal -E utf-8 /app/app/build/gui/qt/../../../../app/server/ruby/bin/sonic-pi-server.rb -u 51235 51236 51237 51237 4560 51238 51239 [-] /var/tmp/sonic-pi-pids/26
Started [39] [-] sh [-] /var/tmp/sonic-pi-pids/39
Started [41] [-] scsynth -u 51237 -a 1024 -m 131072 -D 0 -R 0 -l 1 -i 16 -o 16 -b 4096 -B 127.0.0.1 [-] /var/tmp/sonic-pi-pids/41

```

**Comment by hfiguiere** [comment]
Sadly the log don't show anything obvious and I don't have PopOS, to check.

Do you have pipewire 0.3 installed? If yes which version? It's a requirement for applications requiring JACK like Sonic Pi.

**Comment by SamKomesarook** [comment]
It looks like I have Pipewire (0.3.10-4) installed via apt.

I tried running the application through the command line via:
`flatpak run net.sonic_pi.SonicPi`

and the application failed with the same error, however I got this logging:

```
Gtk-Message: 11:13:52.762: Failed to load module "appmenu-gtk-module"
Gtk-Message: 11:13:52.813: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:13:52.813: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
                                ╘
                         ─       ╛▒╛
                          ▐╫       ▄█├
                   ─╟╛      █▄      ╪▓▀
         ╓┤┤┤┤┤┤┤┤┤  ╩▌      ██      ▀▓▌
          ▐▒   ╬▒     ╟▓╘    ─▓█      ▓▓├
          ▒╫   ▒╪      ▓█     ▓▓─     ▓▓▄
         ╒▒─  │▒       ▓█     ▓▓     ─▓▓─
         ╬▒   ▄▒ ╒    ╪▓═    ╬▓╬     ▌▓▄
         ╥╒   ╦╥     ╕█╒    ╙▓▐     ▄▓╫
                    ▐╩     ▒▒      ▀▀
                         ╒╪      ▐▄

       _____             __        ____  __
      / ___/____  ____  /_/____   / __ \/_/
      \__ \/ __ \/ __ \/ / ___/  / /_/ / /
     ___/ / /_/ / / / / / /__   / ____/ /
    /____/\____/_/ /_/_/\___/  /_/   /_/

   The Live Coding Music Synth for Everyone

            http://sonic-pi.net

[GUI] - reading settings
```
Not sure if the socket warnings are helpful or not...

**Comment by hfiguiere** [comment]
Sadly I'm not sure of what's happening.

**Comment by SamKomesarook** [comment]
Is there any kind of debugging I can do on my machine that might help? I've never had any issues with the channel on Pop! so I'm not too sure...

**Comment by hfiguiere** [comment]
I'm wondering if pipewire 0.3.10 isn't too old. That's the problem with JACK and flatpak apps.

**Comment by SamKomesarook** [comment]
So I added the Ubuntu PPA for pipewire, and upgraded to 0.3.28-1~ubuntu20.10. The GUI still failed to start though, with the same error as listed above.
